name = "products-api"         # Име твојег Worker-а
main = "worker.js"            # Путања до фајла који садржи твој Worker код
compatibility_date = "2025-12-03"

"kv_namespaces": [{
                    "binding": "PRODUCTS",
                    "id": "0c937e9e577544cdbdb4f4deb9738b2d"
                 }]
