name = "products-api"           # Ime Worker-a
main = "worker.js"              # Tvoj Worker fajl
compatibility_date = "2025-12-03"

[[kv_namespaces]]
binding = "PRODUCTS"            # Ovo ime koristi≈° u JS kodu
id = "37a3a42f579c4ed2a343f6a6034a8513"  # ID tvog KV namespace-a
